# *** BLANK MAKEFILE FOR COMPILED LANGUAGE (PYTHON) ***

.PHONY: install run clean

install:
	pip3 install requests

# ported from .gitignore
clean:
	rm -rf __pycache__ *.pyc

# remove RUN per TA feedback